apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: eks-sample-app
spec:
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
  tolerations:
    - operator: Exists
      effect: NoSchedule
